### ISSUE TITLE
Cannot run offline package

### ISSUE THREAD

**Issue by AlexanderMisel** [josStorer/selfhostedAI#3]
```
ERROR:    Traceback (most recent call last):
  File "D:\ChatGLM\python3.10.10\lib\site-packages\starlette\routing.py", line 677, in lifespan
    async with self.lifespan_context(app) as maybe_state:
  File "D:\ChatGLM\python3.10.10\lib\site-packages\starlette\routing.py", line 566, in __aenter__
    await self._router.startup()
  File "D:\ChatGLM\python3.10.10\lib\site-packages\starlette\routing.py", line 656, in startup
    handler()
  File "D:\ChatGLM\.\main.py", line 37, in init
    model = AutoModel.from_pretrained(model_path, trust_remote_code=True, cache_dir=cache_dir)
  File "D:\ChatGLM\python3.10.10\lib\site-packages\transformers\models\auto\auto_factory.py", line 455, in from_pretrained
    model_class = get_class_from_dynamic_module(
  File "D:\ChatGLM\python3.10.10\lib\site-packages\transformers\dynamic_module_utils.py", line 374, in get_class_from_dynamic_module
    return get_class_in_module(class_name, final_module.replace(".py", ""))
  File "D:\ChatGLM\python3.10.10\lib\site-packages\transformers\dynamic_module_utils.py", line 147, in get_class_in_module
    module = importlib.import_module(module_path)
  File "importlib\__init__.py", line 126, in import_module
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1004, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'transformers_modules.local.modeling_chatglm'

ERROR:    Application startup failed. Exiting.
```

**Comment by AlexanderMisel** [comment]
Seems work in the second time.

**Comment by josStorer** [comment]
My new project https://github.com/josStorer/RWKV-Runner, may be better

**Comment by AlexanderMisel** [comment]
Thank you. I'll have a try.
